import { db, sqlite } from "./client";
import { departments, employees } from "./schema";
import { DEPARTMENTS } from "../constants";
import { seedEmployeesFromRandomUser } from "../lib/seedData";



/**
 * Seeds the local SQLite database with demo data for the employee directory.
 * - Creates tables if they do not exist.
 * - Inserts departments from constants if the table is empty.
 * - Fetches and inserts demo employees if the employees table is empty.
 * This function is intended for local/demo use and runs at server startup.
 */
export async function migrateAndSeedIfEmpty() {
  sqlite.exec(
    `CREATE TABLE IF NOT EXISTS departments (
      id integer primary key autoincrement,
      name text not null unique
    );`
  );
  sqlite.exec(
    `CREATE TABLE IF NOT EXISTS employees (
      id integer primary key autoincrement,
      uuid text not null unique,
      name text not null,
      title text not null,
      email text not null,
      location text not null,
      avatar text,
      department_id integer not null references departments(id)
    );`
  );

  const existingDepartments = await db.select().from(departments).limit(1);
  if (existingDepartments.length === 0) {
    await db.insert(departments).values(DEPARTMENTS.map((name) => ({ name })));
  }

  const existingEmployees = await db.select().from(employees).limit(1);
  if (existingEmployees.length > 0) return;

  const departmentRows = await db.select().from(departments);
  const employeesData = await seedEmployeesFromRandomUser(50);

  const departmentIds: number[] = departmentRows.map((department) => department.id);
  if (departmentIds.length === 0) {
    throw new Error("No departments found after initialization");
  }
  // Utility to get the department id from the random department name generated by seedEmployeesFromRandomUser
  const getDepartmentIdByIndex = (index: number): number => departmentIds[index % departmentIds.length] as number;

  await db.insert(employees).values(
    employeesData.map((employee, index) => ({
      uuid: String(employee.uuid),
      name: String(employee.name),
      title: String(employee.title),
      email: String(employee.email),
      location: String(employee.location),
      avatar: String(employee.avatar),
      departmentId: getDepartmentIdByIndex(index),
    }))
  );
}


